
services:
  dev:
    platform: linux/amd64
    build: .
    volumes:
      - .:/chatserver
    command: /bin/bash
    tty: true
    stdin_open: true
    depends_on:
      - database
    networks:
      - chatserver

  server:
    platform: linux/amd64
    build: .
    volumes:
      - .:/chatserver
    command: ./bin/server
    depends_on:
      - database
      - auth-server
    networks:
      - chatserver
      - sql
    ports:
      - "8080:8080"

  client:
    platform: linux/amd64
    build: .
    volumes:
      - .:/chatserver
    command: /bin/bash
    tty: true
    stdin_open: true
    networks:
      - chatserver
    ports:
      - "8082:8082"
    
  database: 
    platform: linux/amd64
    image: mariadb:lts
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    networks:
      - sql
    
  auth-server:
    platform: linux/amd64
    build: .
    volumes:
      - .:/chatserver
    command: ./bin/auth
    depends_on:
      - database
    ports:
      - "8081:8081"
    networks:
      - chatserver
      - sql

networks:
  chatserver:
    driver: bridge
  sql:
    driver: bridge