version: '3'
services:
  dev:
    platform: linux/amd64
    build: .
    volumes:
      - .:/chatserver
    command: /bin/bash
    tty: true
    stdin_open: true

  server:
    platform: linux/amd64
    build: .
    volumes:
      - .:/chatserver
    command: ./bin/server 9002
    environment:
      - PORT=9002
    deploy:
      replicas: 3
    ports:
      - "9002-9004:9002"
    networks:
      - websocket_net

  client:
    platform: linux/amd64
    build: .
    volumes:
      - .:/chatserver
    command: ./bin/client
    networks:
      - websocket_net
networks:
  websocket_net:
    driver: bridge