version: '2.1'

services:
  dev:
    build: .
    volumes:
      - .:/chatserver
    command: /bin/bash
    tty: true
    stdin_open: true


  server:
    build: .
    volumes:
      - .:/chatserver
    command: ./bin/server 
    

  client:
    build: .
    volumes:
      - .:/chatserver
    command: ./bin/client  
